services:
  nextjs-app:
    image: registry.digitalocean.com/chamrong-container/todo-app:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

volumes:
  nextjs_data:
